// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/embyv1/emby.proto

package embyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_embyv1_emby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embyv1_emby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_embyv1_emby_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Configured     bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	BaseUrl        string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_embyv1_emby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embyv1_emby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_embyv1_emby_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *StatusResponse) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *StatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_proto_embyv1_emby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embyv1_emby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_embyv1_emby_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TerminateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionResponse) Reset() {
	*x = TerminateSessionResponse{}
	mi := &file_proto_embyv1_emby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionResponse) ProtoMessage() {}

func (x *TerminateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embyv1_emby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionResponse.ProtoReflect.Descriptor instead.
func (*TerminateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_embyv1_emby_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TerminateSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_embyv1_emby_proto protoreflect.FileDescriptor

const file_proto_embyv1_emby_proto_rawDesc = "" +
	"\n" +
	"\x17proto/embyv1/emby.proto\x12\x18muxcore.playback.emby.v1\"\x0f\n" +
	"\rStatusRequest\"t\n" +
	"\x0eStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\"8\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"@\n" +
	"\x18TerminateSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xeb\x01\n" +
	"\x11EmbyBridgeService\x12[\n" +
	"\x06Status\x12'.muxcore.playback.emby.v1.StatusRequest\x1a(.muxcore.playback.emby.v1.StatusResponse\x12y\n" +
	"\x10TerminateSession\x121.muxcore.playback.emby.v1.TerminateSessionRequest\x1a2.muxcore.playback.emby.v1.TerminateSessionResponseB3Z1github.com/Muxcore-Media/emby/proto/embyv1;embyv1b\x06proto3"

var (
	file_proto_embyv1_emby_proto_rawDescOnce sync.Once
	file_proto_embyv1_emby_proto_rawDescData []byte
)

func file_proto_embyv1_emby_proto_rawDescGZIP() []byte {
	file_proto_embyv1_emby_proto_rawDescOnce.Do(func() {
		file_proto_embyv1_emby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_embyv1_emby_proto_rawDesc), len(file_proto_embyv1_emby_proto_rawDesc)))
	})
	return file_proto_embyv1_emby_proto_rawDescData
}

var file_proto_embyv1_emby_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_embyv1_emby_proto_goTypes = []any{
	(*StatusRequest)(nil),            // 0: muxcore.playback.emby.v1.StatusRequest
	(*StatusResponse)(nil),           // 1: muxcore.playback.emby.v1.StatusResponse
	(*TerminateSessionRequest)(nil),  // 2: muxcore.playback.emby.v1.TerminateSessionRequest
	(*TerminateSessionResponse)(nil), // 3: muxcore.playback.emby.v1.TerminateSessionResponse
}
var file_proto_embyv1_emby_proto_depIdxs = []int32{
	0, // 0: muxcore.playback.emby.v1.EmbyBridgeService.Status:input_type -> muxcore.playback.emby.v1.StatusRequest
	2, // 1: muxcore.playback.emby.v1.EmbyBridgeService.TerminateSession:input_type -> muxcore.playback.emby.v1.TerminateSessionRequest
	1, // 2: muxcore.playback.emby.v1.EmbyBridgeService.Status:output_type -> muxcore.playback.emby.v1.StatusResponse
	3, // 3: muxcore.playback.emby.v1.EmbyBridgeService.TerminateSession:output_type -> muxcore.playback.emby.v1.TerminateSessionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_embyv1_emby_proto_init() }
func file_proto_embyv1_emby_proto_init() {
	if File_proto_embyv1_emby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_embyv1_emby_proto_rawDesc), len(file_proto_embyv1_emby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_embyv1_emby_proto_goTypes,
		DependencyIndexes: file_proto_embyv1_emby_proto_depIdxs,
		MessageInfos:      file_proto_embyv1_emby_proto_msgTypes,
	}.Build()
	File_proto_embyv1_emby_proto = out.File
	file_proto_embyv1_emby_proto_goTypes = nil
	file_proto_embyv1_emby_proto_depIdxs = nil
}
