// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/embyv1/emby.proto

package embyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmbyBridgeService_Status_FullMethodName           = "/muxcore.playback.emby.v1.EmbyBridgeService/Status"
	EmbyBridgeService_TerminateSession_FullMethodName = "/muxcore.playback.emby.v1.EmbyBridgeService/TerminateSession"
)

// EmbyBridgeServiceClient is the client API for EmbyBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbyBridgeServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error)
}

type embyBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbyBridgeServiceClient(cc grpc.ClientConnInterface) EmbyBridgeServiceClient {
	return &embyBridgeServiceClient{cc}
}

func (c *embyBridgeServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EmbyBridgeService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embyBridgeServiceClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateSessionResponse)
	err := c.cc.Invoke(ctx, EmbyBridgeService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbyBridgeServiceServer is the server API for EmbyBridgeService service.
// All implementations must embed UnimplementedEmbyBridgeServiceServer
// for forward compatibility.
type EmbyBridgeServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error)
	mustEmbedUnimplementedEmbyBridgeServiceServer()
}

// UnimplementedEmbyBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbyBridgeServiceServer struct{}

func (UnimplementedEmbyBridgeServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEmbyBridgeServiceServer) TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedEmbyBridgeServiceServer) mustEmbedUnimplementedEmbyBridgeServiceServer() {}
func (UnimplementedEmbyBridgeServiceServer) testEmbeddedByValue()                           {}

// UnsafeEmbyBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbyBridgeServiceServer will
// result in compilation errors.
type UnsafeEmbyBridgeServiceServer interface {
	mustEmbedUnimplementedEmbyBridgeServiceServer()
}

func RegisterEmbyBridgeServiceServer(s grpc.ServiceRegistrar, srv EmbyBridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedEmbyBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmbyBridgeService_ServiceDesc, srv)
}

func _EmbyBridgeService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbyBridgeServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbyBridgeService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbyBridgeServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbyBridgeService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbyBridgeServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbyBridgeService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbyBridgeServiceServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbyBridgeService_ServiceDesc is the grpc.ServiceDesc for EmbyBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbyBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.playback.emby.v1.EmbyBridgeService",
	HandlerType: (*EmbyBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _EmbyBridgeService_Status_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _EmbyBridgeService_TerminateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/embyv1/emby.proto",
}
